apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: expresso
  namespace: expresso
spec:
  tls:
  - secretName: tls-expresso-2018-05-19
  backend:
    serviceName: expresso-ui
    servicePort: 9000

