---
  kind: Service
  apiVersion: v1
  metadata:
    name: expresso-ui
    namespace: expresso
  spec:
    type: NodePort
    selector:
      app: expresso
    ports:
      - protocol: TCP
        port: 9000
        targetPort: 9000
        name: ui