apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: expresso-deployment
  namespace: expresso
  labels:
    app: expresso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expresso
  template:
    metadata:
      labels:
        app: expresso
    spec:
      containers:
      - name: expresso
        image: eu.gcr.io/expresso-today/expresso:latest
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9000
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
          - name: EXPRESSO_OPTS
            valueFrom:
              secretKeyRef:
                name: expresso
                key: options
        args: [
        "-Dplay.http.secret.key=QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n",
        "-Dslick.dbs.default.db.properties.user=postgres",
        "-Dslick.dbs.default.db.properties.password=dpCZeUU83VnsdsfN",
        "-Dslick.dbs.default.db.properties.url=jdbc:postgresql://google/postgres?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=expresso-today:europe-west1:expresso",
        "-Dlogger.resource=logback.prod.xml"]