apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: expresso
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 6379
        args: ["--maxmemory 500mb", "--maxmemory-policy allkeys-lfu"]